apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: my-app-latency
spec:
  groups:
  - name: My App Rules
    rules:
    - record: my_app_latency_avg
      expr: avg(rate(my_app_latency_seconds_sum[5m])) / avg(rate(my_app_latency_seconds_count[5m]))
---

prometheus:
  url: http://prometheus-server.prom.svc.cluster.local
  scrapeInterval: 15s

rules:
  default: false
  custom:
  - seriesQuery: 'my_app_latency_avg'
    resources:
      overrides:
        namespace: {resource: "namespace"}
        pod: {resource: "pod"}
    name:
      matches: "my_app_latency_avg"
    metricsQuery: 'avg_over_time(my_app_latency_avg[5m])'
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: my-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-app
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metricName: my_app_latency_avg
      targetAverageValue: 0.2
